AWSTemplateFormatVersion: "2010-09-09"
Description: 'Route53 entries for Office 365'
Parameters:
  Name:
    Type: 'String'
  HostedZoneId:
    Type: 'AWS::Route53::HostedZone::Id'
  Domain:
    Type: 'String'
  MXPointsTo:
    Type: 'String'
Resources:
  MXRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref 'HostedZoneId'
      Name: !Sub: '${Domain}.'
      Type: 'MX'
      TTL: '3600'
      ResourceRecords: !Sub: '0 ${MXPointsTo}'
  MSOIDRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref 'HostedZoneId'
      Name: !Sub: 'msoid.${Domain}.'
      Type: 'CNAME'
      TTL: '3600'
      ResourceRecords:
        - 'clientconfig.microsoftonline-p.net'
  ADRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref 'HostedZoneId'
      Name: !Sub 'autodiscover.${Domain}.'
      Type: 'CNAME'
      TTL: '3600'
      ResourceRecords:
        - 'autodiscover.outlook.com'
  SIPRecord:
   Type: 'AWS::Route53::RecordSet'
   Properties:
     HostedZoneId: !Ref 'HostedZoneId'
     Name: !Sub: 'sip.${Domain}.'
     Type: 'CNAME'
     TTL: '3600'
     ResourceRecords:
      - 'sipdir.online.lync.com'
  LDRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref 'HostedZoneId'
      Name: !Sub 'lyncdiscover.${Domain}.'
      Type: 'CNAME'
      TTL: '3600'
      ResourceRecords:
        - 'webdir.online.lync.com'
  ERRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref 'HostedZoneId'
      Name: !Sub 'enterpriseregistration.${Domain}.'
      Type: 'CNAME'
      TTL: '3600'
      ResourceRecords:
        - 'enterpriseregistration.windows.net'
  EERecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref 'HostedZoneId'
      Name: !Sub 'enterpriseenrollment.${Domain}.'
      Type: 'CNAME'
      TTL: '3600'
      ResourceRecords:
        - 'enterpriseenrollment.manage.microsoft.com'
  TXTRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref 'HostedZoneId'
      Name: !Sub '${Domain}.' 
      Type: 'TXT'
      TTL: '3600'
      ResourceRecords:
        - '"v=spf1 include:spf.protection.outlook.com -all"'
  SIPSRVTCPRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref 'HostedZoneId'
      Name: !Sub '_sipfederationtls._tcp.${Domain}.'
      Type: 'SRV'
      TTL: '3600'
      ResourceRecords:
        - '100 1 5061 sipfed.online.lync.com.'
  SIPSRVTLSRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneId: !Ref 'HostedZoneId'
      Name: !Sub '_sip._tls.${Domain}.'
      Type: 'SRV'
      TTL: '3600'
      ResourceRecords:
        - '100 1 443 sipdir.online.lync.com'
